### ISSUE TITLE
Checkpoint request

### ISSUE THREAD

**Issue by playdasegunda** [guxm2021/ALT_SpeechBrain#1]
Hello how are you? First I want to congratulate the developers of this tool, which apparently will be very useful, however from what I've been seeing there is not a pre-trained model for us to test the results, I would like to know if it is possible to release the checkpoint model to test this tool in our musics?

Thank you very much in advance,

Lucas Rodrigues.

**Comment by guxm2021** [comment]
Thanks for your interests in our research work. Actually, this repo is implemented based on SpeechBrain (https://speechbrain.github.io). Therefore, we saved and open-sourced our model according to their logic. If you want to test our model on your own dataset. Please follow ALT_SpeechBrain/DALI/ALT/README.md or ALT_SpeechBrain/DSing/ALT/README.md to prepare the trained model and transform your own data into csv files. Then a file will be created to record the WER of each utterance in your file. By the way, if you look at our training code and config files, we have provided an argument to save ".pt" files of our model.
